sudo: false

language: node_js
node_js:
  - 10.16.2

branches:
  only:
    - master

before_install:
  - npm install -g yarn

deploy:
  provider: heroku
  app: ci-reactjs-demo
  api_key:
    secure: ""
